/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BatchButtonPannel.java
 *
 * Created on Jan 8, 2012, 4:06:46 PM
 */
package view.gui;

import util.BasicPublisher;
import util.Subscriber;

/**
 *
 * @author drew
 */
public class BatchButtonPannel extends javax.swing.JPanel {

    private BasicPublisher pub;
    /** Creates new form BatchButtonPannel */
    public BatchButtonPannel() {
        initComponents();
        pub = new BasicPublisher();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        runButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        addTournButton = new javax.swing.JButton();
        removeTournButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        runButton.setText("Run");
        runButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                runButtonMousePressed(evt);
            }
        });

        saveButton.setText("Save Batch");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saveButtonMousePressed(evt);
            }
        });

        addTournButton.setText("Add Tournament");
        addTournButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addTournButtonMousePressed(evt);
            }
        });

        removeTournButton.setText("Remove Tournament");
        removeTournButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeTournButtonMousePressed(evt);
            }
        });

        jButton1.setText("Load Batch");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(removeTournButton)
                .addGap(18, 18, 18)
                .addComponent(addTournButton)
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(runButton)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(addTournButton)
                    .addComponent(removeTournButton)
                    .addComponent(runButton)
                    .addComponent(jButton1))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeTournButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeTournButtonMousePressed
        // TODO add your handling code here:
        pub.notifySubscribers(this, "remove");
    }//GEN-LAST:event_removeTournButtonMousePressed

    private void addTournButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTournButtonMousePressed
        // TODO add your handling code here:
        pub.notifySubscribers(this, "add");
    }//GEN-LAST:event_addTournButtonMousePressed

    private void saveButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMousePressed
        // TODO add your handling code here:
        pub.notifySubscribers(this, "save");
    }//GEN-LAST:event_saveButtonMousePressed

    private void runButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runButtonMousePressed
        // TODO add your handling code here:
        pub.notifySubscribers(this, "run");
    }//GEN-LAST:event_runButtonMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        pub.notifySubscribers(this, "load");
    }//GEN-LAST:event_jButton1MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTournButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton removeTournButton;
    private javax.swing.JButton runButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
    public void addSub(Subscriber sub)
    {
        pub.addSubscriber(sub);
    }
}
