/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BatchStateView.java
 *
 * Created on Feb 26, 2012, 12:44:28 PM
 */
package view.gui;

import control.gui.BatchControl;
import java.rmi.RemoteException;
import javax.swing.SwingUtilities;
import javax.swing.event.TableModelEvent;
import model.game.BatchModel;
import util.ObjectState;
import util.Subscriber;

/**
 *
 * @author drew
 */
public class BatchStateView extends javax.swing.JPanel implements Subscriber{

    private BatchControl control;
    private boolean isTournSub;
    
    /** Creates new form BatchStateView */
    public BatchStateView() {
        initComponents();
        
    }

    public void setBatchControl(BatchControl ctrl)
    {
        if (control != null)
        {
            // so if i had a controller ie for the las batch remove the
            // stuff
            control.removeAllTournSubscriber(this);
            control.removeBatchSub(this);
            control.removeBatchSub(this);
        }
        
        // set the control
        control = ctrl;
        control.addBatchSub(this);
        control.addStartBatchSub(this);
        // then I can set the model so that the
        // table is updated
        jTable1.setModel(control.getBatchModel());
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pauseBt = new javax.swing.JButton();
        ResumeBt = new javax.swing.JButton();
        TermBt = new javax.swing.JButton();
        tournViewBt = new javax.swing.JButton();
        statsBt = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pauseBt.setText("Pause");
        pauseBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pauseBtMousePressed(evt);
            }
        });

        ResumeBt.setText("Resume");
        ResumeBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ResumeBtMousePressed(evt);
            }
        });

        TermBt.setText("Terminate");
        TermBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TermBtMousePressed(evt);
            }
        });

        tournViewBt.setText("More Info");
        tournViewBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tournViewBtMousePressed(evt);
            }
        });

        statsBt.setText("Stats");
        statsBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statsBtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pauseBt)
                .addGap(18, 18, 18)
                .addComponent(ResumeBt)
                .addGap(18, 18, 18)
                .addComponent(TermBt)
                .addGap(18, 18, 18)
                .addComponent(tournViewBt)
                .addGap(18, 18, 18)
                .addComponent(statsBt)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pauseBt)
                    .addComponent(ResumeBt)
                    .addComponent(TermBt)
                    .addComponent(tournViewBt)
                    .addComponent(statsBt))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pauseBtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseBtMousePressed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1)
        control.pauseTourn(control.getBatchModel().getValueAt(jTable1.getSelectedRow(), BatchModel.columns.Tournament.ordinal()).toString());
    }//GEN-LAST:event_pauseBtMousePressed

    private void ResumeBtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResumeBtMousePressed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1)
        control.resumeTourn(control.getBatchModel().getValueAt(jTable1.getSelectedRow(), BatchModel.columns.Tournament.ordinal()).toString());
    }//GEN-LAST:event_ResumeBtMousePressed

    private void TermBtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TermBtMousePressed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1)
        control.termTourn(control.getBatchModel().getValueAt(jTable1.getSelectedRow(), BatchModel.columns.Tournament.ordinal()).toString());
    }//GEN-LAST:event_TermBtMousePressed

    private void tournViewBtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournViewBtMousePressed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1)
        {
            TournGamesView.control = control.getTournControls().get(jTable1.getSelectedRow());
            TournGamesView.main(null);
        }
    }//GEN-LAST:event_tournViewBtMousePressed

    private void statsBtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsBtMousePressed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1)
        {
            TournamentAgentsView.cont = control.getTournControls().get(jTable1.getSelectedRow()).getTournPropertiesControl().getAgentChooser();
            TournamentAgentsView.main(null);
        }
    }//GEN-LAST:event_statsBtMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResumeBt;
    private javax.swing.JButton TermBt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pauseBt;
    private javax.swing.JButton statsBt;
    private javax.swing.JButton tournViewBt;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Object pub, Object code) throws RemoteException {
        // So I get updated on the status of the tourn
        // change the text in the table
        // by calling the tableChanged and telling it which row changed
        // by querrying the index of 
        if (pub instanceof BatchControl)
        {
            // this means that the update means that this is the start of the
            // batch so i should update the model
            jTable1.setModel(control.getBatchModel());
        }
        
        System.out.println("UPDATED BatchStateView");
        if (isTournSub == false)
        {
            control.addAllTournSubscriber(this);
            isTournSub = true;
        }
        jTable1.tableChanged(new TableModelEvent(jTable1.getModel()));
       // jTable1.invalidate();
        //jTable1.repaint();
         
        //jTable1.tableChanged(new TableModelEvent(jTable1.getModel(), control.getTournNames().indexOf(code)));
    }
}
