/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TournamentAgentView.java
 *
 * Created on Mar 10, 2012, 2:30:23 PM
 */
package view.gui;

import control.gui.AgentChooserControl;
import control.gui.TournamentPropertiesController;
import info.monitorenter.gui.chart.Chart2D;
import info.monitorenter.gui.chart.ITrace2D;
import info.monitorenter.gui.chart.axistickpainters.AxisTickPainterDefault;
import info.monitorenter.gui.chart.traces.Trace2DBijective;
import info.monitorenter.gui.chart.traces.Trace2DSimple;
import info.monitorenter.gui.chart.traces.computing.Trace2DArithmeticMean;
import info.monitorenter.gui.chart.traces.computing.Trace2DArithmeticMeanY;
import info.monitorenter.gui.chart.views.ChartPanel;
import java.awt.Panel;
import java.util.Random;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import util.AgentDataCollector;

/**
 *
 * @author drew
 */
public class TournamentAgentsView extends javax.swing.JFrame {

    private Chart2D chart;
    private ChartPanel pan;
    public static AgentChooserControl cont;
    private String oldAgentItem = "";
    private String oldTraceItem = "";
    private AgentDataCollector cl;
    /** Creates new form TournamentAgentView */
    public TournamentAgentsView() {
        initComponents();
    
        
        agentList.setModel(new DefaultComboBoxModel(cont.getChosen().toArray()));
    // Create a chart:  
    chart = new Chart2D();
    pan = new ChartPanel(chart);
    jPanel1.add(pan);
    pan.setSize(jPanel1.getSize());
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agentList = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        traceNameList = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jLabel1.setText("Agent:");

        agentList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        agentList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentListActionPerformed(evt);
            }
        });

        jLabel2.setText("Data:");

        traceNameList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        traceNameList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traceNameListActionPerformed(evt);
            }
        });

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agentList, 0, 148, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(traceNameList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agentList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(traceNameList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentResized

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
        // TODO add your handling code here:
        
        pan.setSize(jPanel1.getSize());
        pan.repaint();
    }//GEN-LAST:event_jPanel1ComponentResized

    private void agentListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentListActionPerformed
        // TODO add your handling code here:
         JComboBox cb = (JComboBox)evt.getSource();

        // Get the new item
        String newItem = (String)cb.getSelectedItem();

        // Determine if different from previously selected item
        boolean same = newItem.equals(oldAgentItem);
        oldAgentItem = newItem;
        if ("comboBoxChanged".equals(evt.getActionCommand())) {
            // User has selected an item; it may be the same item
            if (!same)
            {
                traceNameList.removeAllItems();
                traceNameList.setModel(new DefaultComboBoxModel(cont.getTraceNames(newItem).toArray()));
                //cont.getTraceNames(newItem);
            }
        }
        
    }//GEN-LAST:event_agentListActionPerformed

    private void traceNameListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traceNameListActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();

        // Get the new item
        String newItem = (String)cb.getSelectedItem();

        // Determine if different from previously selected item
        if (newItem != null)
        {
            boolean same = newItem.equals(oldAgentItem);
            oldTraceItem = newItem;
            if ("comboBoxChanged".equals(evt.getActionCommand())) {
                // User has selected an item; it may be the same item
                if (!same)
                {
                    chart.removeAllTraces();
                    //chart.setAxisTickPainter(new AxisTickPainterDefault());
                    //ITrace2D trace = new Trace2DBijective();
                    Trace2DArithmeticMean trace = new Trace2DArithmeticMean(10);
                    chart.addTrace(trace);
                    
                    if (cl != null && cl.isRunning())
                    {
                        cl.stop();
                    }
                    
                    //trace.addComputingTrace(new Trace2DArithmeticMean(444));// checking this out
                    cl = cont.getAgentDataCollector(oldAgentItem, newItem, trace);
                    if (cl.shouldStart() == true)
                    {
                        cl.start();
                    }
                }
            }
        }
    }//GEN-LAST:event_traceNameListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TournamentAgentsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TournamentAgentsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TournamentAgentsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TournamentAgentsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TournamentAgentsView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox agentList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox traceNameList;
    // End of variables declaration//GEN-END:variables
}
